version: '3.8'

services:
  backend:
    build:
      context: ./nurse-track-back
      dockerfile: Dockerfile
    container_name: nursetrack-backend
    restart: 'no'
    ports:
      - '8080:8080'
    environment:
      # Simplificamos la URL a una sola línea para evitar problemas de espacios/saltos
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/nurse-track-back?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''
      # Ya no sobrescribimos ddl-auto aquí, toma el valor de application.properties
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_SHOW_SQL: 'true'
    depends_on:
      # ¡CAMBIO CLAVE AQUÍ! Esperamos a que el servicio MySQL esté 'healthy'
      mysql:
        condition: service_healthy
    # Quitamos la sección volumes del backend si no la usas para desarrollo en caliente
    # Ya que el Dockerfile copia los archivos.
    # Si quieres hot-reloading de código, necesitarías un setup más avanzado.

  mysql:
    image: mysql:8.0
    container_name: nursetrack-mysql
    restart: always
    environment:
      MYSQL_DATABASE: nurse-track-back
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    healthcheck: # Ya tenías un healthcheck, lo cual es excelente
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
